### ISSUE TITLE
Typescript Migration

### ISSUE THREAD

**Issue by tapas4java** [rolandjitsu/ng2-play#1]
It would be more helpful if you could drop the traceure dependency and migrate to Typescript.

**Comment by rolandjitsu** [comment]
@tapas4java I've actually considered that to begin with, however I really do not like the RoR-like syntax for including references `/// <reference path="../typings/jquery.d.ts"/>`.

I'll look into it anyway, maybe I'll make a different branch. I also have to see how to make the build process as simple as possible (so that users don't have to do too much to get started).

**Comment by tapas4java** [comment]
Thank you very much! I know there are many rough edges but everything is going to change in coming couple of months. I really aprriciate if you could have a look at Angular2  Material repo even though it is in early stage.

This could be the best Angular2 seed app if everything works together. Let me know if in any way i can help. Thanks!

**Comment by rolandjitsu** [comment]
@tapas4java please create another issue for Angular 2 Material and I will look into it :)

**Comment by tapas4java** [comment]
Created #2

**Comment by rolandjitsu** [comment]
@tapas4java I have switched to TS now :)
